---
- hosts: localhost
  name: docker build

  tasks:
    - name: create docker image
      shell: docker build -t prj:latest .
      args:
        chdir: /root/team1

    - name: change docker tag
      shell: docker tag prj:latest alsgp96/prj_devops:latest

    - name: push docker image
      shell: docker push alsgp96/prj_devops:latest
